### ISSUE TITLE
Refactor code to prepare for security audit

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#108]

**Comment by Qkyrie** [comment]
any todo's that can be picked up here?

**Comment by maraoz** [comment]
I don't have any concrete tasks to list, my plan was to traverse the whole codebase and check that code style is good, and easy to understand. If you read our code audits you'll see I mention a lot of advice to make the auditor's life easier. If you're interested, feel free to read them and apply similar ideas to Zeppelin:
- https://medium.com/zeppelin-blog/ethercamps-projectkudos-public-code-audit-179ee0c6672d#.2r909r9rz
- https://medium.com/zeppelin-blog/golem-network-token-gnt-audit-edfa4a45bc32#.fdb6kf20d
- https://medium.com/zeppelin-blog/arcade-city-arc-token-audit-9071fa55a4e8#.w2hm1kqpe
- https://medium.com/zeppelin-blog/ethercamps-hacker-gold-hkg-public-code-audit-b7dd3a2fe43b#.lilgtncq9
- https://medium.com/zeppelin-blog/onward-with-ethereum-smart-contract-security-97a827e47702#.6gku925cm

**Comment by Qkyrie** [comment]
Will definitely do!

**Comment by veox** [comment]
Any thoughts on making documentation with Doxygen, instead of the current Sphinx? In particular, Solidity docs [mention](https://solidity.readthedocs.io/en/develop/layout-of-source-files.html#comments) Doxygen-like comments, as does [this wiki page about NSF](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format).

Making documentation inline with code could improve general doc quality, or at least highlight what's missing. This could make an auditor's life easier, and maybe a general user's, too.

This would mean switching doc-gen machinery, though, which will complicate things for the project maintainers. Sphinx can't directly handle non-Python code with Doxygen-style comments AFAIK, but it can use [an extension, `breathe`](https://breathe.readthedocs.io/en/latest/quickstart.html), to generate from Doxygen-produced XML, like [described in this SO answer](http://stackoverflow.com/a/11249722/7056908). That would mean having two doc-gen systems instead of one, though.

**Comment by veox** [comment]
OTOH, it may be simpler to extract Doxygen-style comment lines from `.sol` files, format them a bit, and dump to respective `.rst` files for Sphinx to handle. Essentially the same as now, but scripted instead of manual.

**Comment by maraoz** [comment]
@veox I like that idea

**Comment by veox** [comment]
Heh, which one?

I've accidentally started working on the latter, [here's WIP so far](https://github.com/veox/zeppelin-solidity/blob/doc-update-from-source/docs/update.py).

What this increasingly looks like, though, is a [custom Sphinx domain for Solidity](http://www.sphinx-doc.org/en/stable/domains.html).

There turns out to be a Sphinx extension for this, too - [domaintools](https://bitbucket.org/klorenz/sphinxcontrib-domaintools). Using that, however, would probably require modifications to the doc-building machine. It seems [this is possible with readthedocs](https://docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc).

**Comment by veox** [comment]
To clarify, there is still need to _extract_ the natspec before passing to Sphinx. A custom Sphinx domain is not strictly necessary - something similar, like Javascript, could probably be used.

**Comment by maraoz** [comment]
@veox The latter :) would you like to open a new issue for that? I'm closing this issue based on work on this PR: https://github.com/OpenZeppelin/zeppelin-solidity/pull/146
