### ISSUE TITLE
Add Danger CI bot to Zeppelin repo

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#153]
See http://danger.systems/

**Comment by rudygodoy** [comment]
I've already setup Danger and tested locally with a simple rule, which basically prints a message.

`message(":tada:, this worked @" + danger.github.pr.user.login)`

A few questions for this one:

- Does the project use Travis CI? If not which one would you want to integrate with?
- Do you have an idea of the rules you want to setup initially? Since this is more like a cultural consensus among project members I guess we can follow Danger's suggestion and start with 0 then adding rules gradually.

**Comment by frangio** [comment]
Closing as stale. We seem to be doing fine currently with Travis CI's GitHub integration.
