### ISSUE TITLE
Improve Shareable code quality

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#199]
`Shareable` needs some work. From the audit: 

- Doesn’t check if _required <= len(_owners) for instance, that would be a bummer. What if _required were like MAX - 1?
- I have a general concern about the difference between owners, _owners, and owner in Ownable.sol. I recommend “Owners” be renamed. In general we do not recomment single character differences in variable names, although a preceding underscore is not uncommon in Solidity code.
- Line 34: “this contract only has six types of events”. . . actually only two.
- Line 61: Why is ownerIndex keyed by addresses hashed to uints? Why not use the addresses
directly, so ownerIndex is less obscure, and so there’s stronger typing?
- Line 62: Do not love ++i) ... owners[2+ i]. Makes me do math, which is not what I want to do.
I want to not have to do math.
- Move execute function from `MultisigWallet` to `Shareable`.

**Comment by DavidKnott** [comment]
@maraoz I'll get working on this.

**Comment by DavidKnott** [comment]
@maraoz I think it'd be simpler if the ```Shareable contract``` creator passed themselves in as an owner in the ```owners``` argument if the want be one instead of automatically adding the ```msg.sender``` in the constructor.

Also I'm a little confused why there should be a mapping and an array for keeping track of owners.
It seems like:
```mapping(address => bool) ownerIndex;```
Should be enough to keep track of owners.  As opposed to:
```mapping(address => uint) ownerIndex;``` and ```address[256] owners;```

**Comment by frangio** [comment]
Closed by #328.
