### ISSUE TITLE
Wrong balances comparison

### ISSUE THREAD

**Issue by misteraverin** [OpenZeppelin/zeppelin-solidity#213]
@maraoz SEVERE BUG

In `test/Destructible.js` you compare two balances as normal numbers, but they are BigNumber instances from BigNumber Library.
```
 let initBalance = web3.eth.getBalance(owner);
 // send 10 ether to address, newBalance must be bigger than initBalance
 let newBalance = web3.eth.getBalance(owner);
 assert.isTrue(newBalance > initBalance); // booms, it fails
{ [String: '109007855400000000000'] s: 1, e: 20, c: [ 1090078, 55400000000000 ] } // newBalance
{ [String: '99007855400000000000'] s: 1, e: 19, c: [ 990078, 55400000000000 ] } // initBalance
```
Yeah, they are compared as strings. So please use `greaterThan` function.

**Comment by frangio** [comment]
Thanks for reporting @misteraverin!

Are the tests actually failing for you? If they are it must be for some other reason. Are you running them as `npm test`?

As you've observed the assertion doesn't fail because JavaScripts coerces the BigNumber instances to strings before comparing them. This works but isn't very nice though, that's true. We have an open issue for it, see #204.

**Comment by misteraverin** [comment]
@frangio current tests are not failing, cause balances are OK. But i test with other balances and it fails.

**Comment by misteraverin** [comment]
@frangio Actually BigNumber lib already provides us `greaterThan` method for comparing. In ideal world we want exception in tests when BigNumber compared with `>, <, >=, <= `. But we should think about a more realistic way (actually first option isn't magic, but writing static-analysis tool for this is too complicated).

**Comment by frangio** [comment]
I can reproduce. Let's continue the discussion in #204 if you want.
