### ISSUE TITLE
Make Ownable's owner configurable in construction time

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#262]
Right now, `msg.sender` is made the contract's owner. Make `Ownable`'s constructor receive an address

**Comment by rstormsf** [comment]
Seems like Ownable.sol depends on so many contracts and I"m getting:
```
The contract code couldn't be stored, please check your gas amount.
```
error.

**Comment by AugustoL** [comment]
@rstormsf, I think it can be because you compare to 0 an address or if not it seems that you have reach the gas limit.

@maraoz why do we need it? the ownership can be changed after the contract creation with transferOwnership. What happens if Ownable is used on a contract that receives as first argument of the constructor an uint256 ?

**Comment by DavidKnott** [comment]
@AugustoL @rstormsf   I'm not sure how an else statement would work because if we want the to pass in the `owner` on creation I think we should have it happen all the time.  To me a conditional statement in `Ownable()` seems like it adds needless complexity (it seems like you'd have to pass in `0x0` as a place holder to use the `else` with msg.sender).

**Comment by rstormsf** [comment]
So, should I continue doing it? or we leave `msg.sender` as a way to declare an owner. ? 
I personally think since it will take more gas, we should prob leave `msg.sender` cause so many other contracts depend on it. Thoughts?

**Comment by AugustoL** [comment]
+1 on leaving msg.sender

**Comment by maraoz** [comment]
By community consensus, I'm closing this issue. 
You can still always call `ownable.transferOwnership(newOwner)` after creating the contract.
Thanks guys for the discussion.
