### ISSUE TITLE
Refactor vesting mechanics into external TokenVesting contract

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#274]
Currently, vesting of tokens is implemented via the `VestedToken` token contract. 
After reading the [Trustless SNT Selling Contract](https://www.reddit.com/r/ethtrader/comments/6ip2vg/trustless_snt_selling_contract/) contract, I realized a more elegant solution would be to implement vesting of tokens in the contract holding the tokens, not in the token contract.

I propose moving the vesting mechanics to a new contract, dubbed `TokenVesting`, which holds tokens, and releases them in time to another address according to a vesting schedule. This takes all the complex vesting mechanics away from the token contract, reducing the potential attack surface. 
I think this may be the way to add features to tokens without making their code grow too much: externalizing them to other contracts.

**Comment by izqui** [comment]
I completely agree with this and was something audits to the Aragon token pointed out after the source code was already locked but decided against modifying it close to the sale.

The only advantage I still see on having the vesting in the token itself is that if a vested holder follows the vesting schedule and only tries to spend their tokens when they can, they won't even experience there was a vesting at all, as they will be able to just interact with the token contract. 

What I think would solve this is if the contract that held the tokens and applied the vesting conformed to ERC20 to some extent. This way people could use already existing tools that interact with tokens to transfer the tokens when the time comes, the only difference is that they would need to perform the transfer in the token holding contract instead of the proper token.

**Comment by federicobond** [comment]
A thousand times yes!

**Comment by frangio** [comment]
The same mechanism is used by [TokenTimelock](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/TokenTimelock.sol).

**Comment by SylTi** [comment]
I would advise completly abstracting the vesting, so you could also make EtherVesting => allow people to slowly release the found of a crowdsales

**Comment by maraoz** [comment]
Great idea @SylTi !

**Comment by izqui** [comment]
I made an EtherToken implementation for Aragon on top of Zeppelin that
could easily be incorporated for this purpose
https://github.com/aragon/aragon-core/blob/master/contracts/tokens/EtherToken.sol

**Comment by maraoz** [comment]
Completed in https://github.com/OpenZeppelin/zeppelin-solidity/pull/476
