### ISSUE TITLE
Fix coveralls integration

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#291]
Currently broken:
https://coveralls.io/github/OpenZeppelin/zeppelin-solidity

**Comment by cgewecke** [comment]
@maraoz Have you considered [codecov.io](https://codecov.io/) as a possible alternative? Not sure what's going on with coveralls but it sometimes seems like their integration with github is less reliable than it used to be - things don't sync etc.

**Comment by maraoz** [comment]
I haven't tried it but I'm open :)

**Comment by cgewecke** [comment]
Ok I'll look into this tomorrow (unless someone does it before then).

**Comment by cgewecke** [comment]
FWIW I'm not even able to generate coverage locally for Zeppelin because Truffle (or testrpc?) are hitting node's V8 memory limit (1.7 MB!) while trying. It gets past the compilation step and eventually crashes with: `Allocation failed - JavaScript heap out of memory`

Going to have to look into this further. . . . the initial coverage reports might have been on the very edge of what the VM can handle and now 100 commits later it's over the line. 

The travis container is 4MB so there's some hope anyway.

**Comment by maraoz** [comment]
@cgewecke which node version?
I'm running v8.0.0 and `npm run coverage` is not giving a `JavaScript heap out of memory` error, although it does fail for different reasons.

**Comment by cgewecke** [comment]
@maraoz Interesting . . . I think I ran it on 6.9.x following the README. Are you getting past the compilation step and into the tests with 8? 

There is a new version of testrpc that has a much smaller memory footprint so I've been thinking that it might just be a question of upgrading solidity-coverage's rpc fork.

**Comment by maraoz** [comment]
My run dies here:

```
Instrumenting  ./coverageEnv/contracts/token/VestedToken.sol
Launching test command (this can take a few seconds)...
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/maraoz/git/zep/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/home/maraoz/git/zep/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/maraoz/git/zep/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/maraoz/git/zep/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/home/maraoz/git/zep/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/home/maraoz/git/zep/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
Cleaning up...

    There was an error generating coverage. Possible reasons include:
    1. Another application is using port 8555 
    2. Truffle crashed because your tests errored
    
  Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
npm ERR! code ELIFECYCLE

```

**Comment by cgewecke** [comment]
@maraoz 
Good news: Have resolved running coverage on Zeppelin locally for Node6/ Node7.
Bad news: Running the unit tests and coverage back to back looks like its maxing out the memory limits in CI container. Process just gets killed.    

Options:
+ Run your unit tests as coverage tests . . . but they're very different - the gas limits are fake and tons of events are injected into the code. Seems questionable. 

+ Run coverage locally and send the data directly to coveralls so that the reports are available to people who want to see them, but that's not CI integration i.e. automated feedback on PRs so that you can evaluate their propriety. 

+ Have two CI services: Travis for unit tests, CircleCI for coverage. What do you think? Is that too obnoxious? Let me know . . . I'll add a circle.yml to my pending PR to fix this.

**Comment by cgewecke** [comment]
Assuming it's possible, I'm not sure it is.

**Comment by federicobond** [comment]
Can you try Travis with `sudo: required` environment? It comes with almost double the memory apparently: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

**Comment by cgewecke** [comment]
[Running it now](https://travis-ci.org/cgewecke/zeppelin-solidity/builds/252197680).

**Comment by cgewecke** [comment]
@federicobond 🎉  🎉  🎉  So happy. Thank you.
