### ISSUE TITLE
Change crowdsales to use timestamps instead of block numbers

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#350]
Due to the difficulty bomb it is very hard to estimate block numbers.

**Comment by SCBuergel** [comment]
Some thoughts from my end (cross post from Slack)
For now you are generally using `block.number` instead of `block.timestamp`.
*Advantages* of what you do:
- `block.number` will always increase by one compared to previous block, this is guaranteed by the protocol.
- `block.timestamp` can be minimally gamed by a miner, see [here](https://ethereum.stackexchange.com/questions/10941/is-solidity-block-number-more-secure-than-timestamp) and [here](https://ethereum.stackexchange.com/questions/5927/how-would-a-miner-cope-with-a-huge-block-time)
*Disadvantages*:
- the future block time is unknown and leads to surprises, especially with the latest difficulty bomb and ice age forks. 
Given that ICOs usually run over several days, *the in-accuracy due to unknown block times is actually higher than the max 15 minutes practical gamability of the `block.timestamp`*. Hence I’d suggest to use `block.timestamp` (or `now`) instead of `block.number` for your crowdsale contract.

**Comment by frangio** [comment]
Thank you for your thoughts @SCBuergel. I agree with all of them. We have done the change because of the disdvantage you stated, and the reasoning that it's a good trade-off for crowdsales.

**Comment by DaveAppleton** [comment]
Finally.

Months ago I reported that the ethereum team members had agreed that a block time could not be gamed by more than a few seconds. Certainly not the 15 minutes mentioned above. 

The original comment was to prevent it being used for things like rand seeds.
