### ISSUE TITLE
Safemath add function integer overflow check

### ISSUE THREAD

**Issue by hh3755** [OpenZeppelin/zeppelin-solidity#365]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/6e66ba321e545c7840f51ba978a0dd9aaad3ad99/contracts/math/SafeMath.sol#L27-L31

Here `assert(c >= a);`  should we check `a` and `b` both for a unsigned integer overflow ?

Maybe I missed something, If I'm wrong,please pointing out,thank you.

**Comment by frangio** [comment]
Hi @hh3755! Thanks for the reaching out.

It actually suffices to check that `c >= a`. A small proof follows.

We will see that it cannot be that there is overflow and `c >= a` is true. Suppose there is overflow, then under the usual arithmetic `c = a + b - M` (where `M = 2**256` is the maximum `uint256` plus one), because the addition wraps around. If `c >= a` we can replace to get `a + b - M >= a`. cancelling and reordering terms we get `b >= M`, but this is a contradiction because `b` is a `uint256` and thus `b < M`.
