### ISSUE TITLE
Check that destination of token transfers is not 0x

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#400]
Do we want to add `require(_to != address(0))` to `transfer` and `transferFrom`?

**Comment by SylTi** [comment]
Why? You can have use cases that need to send funds to a non-accessible address.
And why only checking for a null address? why not also check for validity?

**Comment by frangio** [comment]
What does it mean to check for validity?

In general we add checks for the null address because uninitialized values in the EVM are zero values. It helps prevent errors. A use-case where it's needed to make tokens inaccessible would be better served by a custom (non-ERC20) function that removes the tokens from circulation.

**Comment by SylTi** [comment]
What I mean by invalidity is non-redeemable address like 0xDead, 0x1 etc.

I agree, but you can't make that error by forgetting a parameter, the function takes 2, so you must provide 0x0 manually or the EVM will throw because of the invalid number of arguments.

**Comment by frangio** [comment]
The thing is there is no way to identify that an address is non-redeemable. Any address is potentially non-redeemable if no user has a private key for it (and it's not a contract address).
