### ISSUE TITLE
approve should not work on paused PausableToken

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#401]
Not 100% sure, but let's discuss

**Comment by frangio** [comment]
My intuition is that `Pausable` should make all public non-constant functions stop working, except for some emergency mechanism that the owner can activate.

**Comment by pash7ka** [comment]
May be I'm wrong, but in my opinion purpose of PausableToken is to allow non-atomic or time-consuming tasks to be executed while balances are immutable.
For example, if you need to count votes this may require a few transactions because of gas limit. So you can pause transfers while you are counting. Or you may decide to pause during whole voting process to make things simple.
But in both this examples you don't need to pause approve, because it doesn't change balances.

Is there an example where pausing approves is required?

**Comment by frangio** [comment]
@pash7ka I like your reasoning and it may be a good use case, but I don't think it's aligned with the purpose of `Pausable`.

We consider `Pausable` to be an ["emergency stop" mechanism](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/lifecycle/Pausable.sol#L9). The problem with this mechanism is that one must manually add `whenNotPaused` modifiers to all the relevant functions. The `PausableToken` contract, then, is intended to be a `StandardToken` for which this job has already been done.

In this scenario, an example where pausing approves is required would be a `PausableToken` which has been extended with buggy logic that makes use of the approval data. What do you think of this?

Pausing transfers to "make things simple" doesn't sound like a good idea to me. If token transfers were involved in some voting process I would extend the `transfer` function to log votes elsewhere if the contract is in a voting period.

**Comment by 7flash** [comment]
Another user case is to freeze trading during the crowdsale. I think approve is an element of trading and it should be paused also.

**Comment by pash7ka** [comment]
@frangio I do understand the idea of PausableToken as a ready to use Pausable StandartToken. And you are right, somebody may use approval data and think it will be also paused.
So After your explanation I'm fine with making approve() pausable.
