### ISSUE TITLE
The operation for multisig functions must have an intrinsic hash

### ISSUE THREAD

**Issue by tavitohanian** [OpenZeppelin/zeppelin-solidity#429]
reference 1: documentation comments above modifier onlymanyowners(bytes32 _operation) in file zeppelin-solidity/contracts/ownership/Shareable.sol wants the operation hash to be intrinsic.

reference 2: function confirm(bytes32 _h) onlymanyowners(_h) returns (bool) confirms and checks that the multisig operation can be executed based on this hash (_h) that is computed in function execute(address _to, ... as: 
    // determine our operation hash.
    _r = keccak256(msg.data, block.number);

Is it not possible for multisig operation transactions from different owners to straddle/fall-into different block numbers? is there an issue here?

Thanks

**Comment by tavitohanian** [comment]
from my package.json:
  "_from": "zeppelin-solidity",
  "_id": "zeppelin-solidity@1.2.0",

**Comment by frangio** [comment]
Thanks for reporting @tavitohanian!

MultisigWallet is no longer part of OpenZeppelin as of #328, so I will close this issue.

However, the question is interesting, and the piece of code can be found live in [ethereum/dapp-bin](https://github.com/ethereum/dapp-bin/blob/master/wallet/wallet.sol#L343-L363). The `block.number` is acting as a nonce, so that the same parameters can be used for a multisig transaction at different moments. (We want to be able to send 1 ether to John today, and again tomorrow, and have those two transactions receive different transaction hashes.)

It is an issue if you intend to confirm an existing transaction using `execute`, but this is not the usual way to go about it. Instead, once a proposal for a transaction is submitted, the rest of the owners will use the generated hash and call `confirm` on it.
