### ISSUE TITLE
CappedCrowdsale.sol missing parent constructor

### ISSUE THREAD

**Issue by VogtAI** [OpenZeppelin/zeppelin-solidity#449]
Shouldn't the parent constructor be called?

currently:
`  function CappedCrowdsale(uint256 _cap) {
    require(_cap > 0);
    cap = _cap;
  }`

proposed:
`  function CappedCrowdsale(uint256 _cap, uint256 _startTime, uint256 _endTime, uint256 _rate, address _wallet) Crowdsale(_startTime, _endTime, _rate, _wallet) {
    require(_cap > 0);
    cap = _cap;
  }`

**Comment by SCBuergel** [comment]
I use this `CappedCrowdsale` as a base contract. Then I call both base constructors:

```
contract MyCrowdSale is CappedCrowdsale {
    function MyCrowdSale(uint256 _cap, uint256 _startTime, uint256 _endTime, uint256 _rate, address _wallet) CappedCrowdsale(_cap) Crowdsale(_startTime, _endTime, _rate, _wallet) {
}
```

This approach seems a bit cleaner than passing constructor arguments through to the base constructor.

**Comment by benjohnson2001** [comment]
This notation seems very confusing to me. I think it would make more sense if CappedCrowdsale called `super(_startTime, _endTime, _rate, _wallet)` and required its parent's constructor arguments.

**Comment by frangio** [comment]
Thanks for bringing this up! This is not a bug but a feature of Solidity we decided to use. Let me clarify.

Since the contracts are designed to use multiple inheritance, they need to be defined like this because otherwise the base constructor can be called different times with different arguments. There is no warning when this happens, as seen in [this example](https://remix.ethereum.org/#version=soljson-v0.4.16+commit.d7661dd9.js&gist=db66390655e34bded256eb4300c8f825). In this case, contract `B` is making an assumption on the value of `a`, which holds if `B` itself is instantiated, but which doesn't necessarily hold for child contracts.

This feature prevents such a bug from happening because the child contract cannot assume the constructor parameters that were used for the parent constructor.
