### ISSUE TITLE
RefundableCrowdsale is not aligned with RefundVault

### ISSUE THREAD

**Issue by rstormsf** [OpenZeppelin/zeppelin-solidity#485]
Intro:
In order to use [RefundableCrowdsale](https://github.com/OpenZeppelin/zeppelin-solidity/blob/5cf503673faea92c1b5c615c3f8358febf06e160/contracts/crowdsale/RefundableCrowdsale.sol), you have to have [RefundVault](https://github.com/OpenZeppelin/zeppelin-solidity/blob/5cf503673faea92c1b5c615c3f8358febf06e160/contracts/crowdsale/RefundVault.sol)

I have spotted a few problems:

1. In order to deposit into the vault, you have to give ownership of vault contract to crowdsale
Once you do that, you won't be able to call other functions such as `close`, and `enableRefunds` because the owner is crowdsale.
So, I assume that RefundableCrowdsale is missing a few methods for those proxy calls in order to gain full control of the vault. 

Also, unit test coverage is very poor for RefundableCrowdsale, not covering all cases. 

I'm curious what was the system design for RefundableCrowdsale + RefundVault

**Comment by frangio** [comment]
Thanks for reporting @rstormsf! The `close` and `enableRefunds` functions you mentioned are called as part of `finalization` in `RefundableCrowdsale`. Take a look [here](https://github.com/OpenZeppelin/zeppelin-solidity/blob/5cf503673faea92c1b5c615c3f8358febf06e160/contracts/crowdsale/RefundableCrowdsale.sol#L47-L51).

The idea was to make it trustless, which is why only the crowdsale contract has the permissions to call them.

If you want to improve coverage it will be a very welcome PR!

**Comment by rstormsf** [comment]
Ohh I see @frangio makes sense now.
