### ISSUE TITLE
Change code linter to Solhint

### ISSUE THREAD

**Issue by idrabenia** [OpenZeppelin/zeppelin-solidity#508]
Hi guys!

Solium works slow and does not cover all style guide rules. 

We develop linter that allow to verify style guide, security and best practices issues! There is Solhint - https://github.com/protofire/solhint

I believe it will be very helpful for your project!

**Comment by maraoz** [comment]
@idrabenia mind creating a PR with this change? :)

**Comment by idrabenia** [comment]
@maraoz Sure!  ;)

**Comment by idrabenia** [comment]
We may do this in next way:
1. Only add config and run scripts
2. No 1 + Fix all linter errors

Which option are you think would be more suitable for your project?

\- Ilya

**Comment by frangio** [comment]
Hi @idrabenia! Do you mind pointing out what style guide rules are not covered by Solium?

This repo has a pretty old version of Solium set up but we're probably going to upgrade it soon. (#556)

**Comment by duaraghav8** [comment]
Hi @frangio, 2 rules aren't covered by Solium from style guide:
- [Source file encoding](http://solidity.readthedocs.io/en/develop/style-guide.html#source-file-encoding) 
- [Order of functions](http://solidity.readthedocs.io/en/develop/style-guide.html#order-of-functions)

Hopefully I'm not missing out any.

Rules available:
- Style guide - http://solium.readthedocs.io/en/latest/user-guide.html#list-of-core-rules
- Security (these rules come packed with solium) - https://github.com/duaraghav8/solium-plugin-security/tree/661c2b4f1ea0aa1fea95a78abc3d2287d63f3048#list-of-rules

**Comment by idrabenia** [comment]
Hi @frangio ,

"Do you mind pointing out what style guide rules are not covered by Solium?"
1. Expressions align (style guide specifying rules to align all type of expressions (+, -, new, delete, /, %, etc)
2. Statements align (alignment of if / while / do - Style Guide specifying set of restrictions to this constructions)
3. Functions alignment rules
4. Array declaration restrictions
5. Indent is more precise in Solhint
6. Function ordering
7. Visibility modifier ordering

Futhermore Solhint provide possibilities to control complexity of the code - 
1. Restrict cyclomatic complexity of method
2. Restrict count of fields in contact
3. Restrict length of line

You may see count of error in latest version of Solhint
https://gist.github.com/idrabenia/39cfd10839f9c5755aab87b309b26fd0

and latest version of Solium 
https://gist.github.com/idrabenia/36797ebd765ee2df36ce310c177b1e27

As you may see Solhint find x2.5 more issue than solium. And made it x2 faster.

**Comment by idrabenia** [comment]
Further more,

1. Solhint trying to close all created issues during week, you will not wait years to fix some urgent problem.
2. We want to create high quality product - our **code coverage is 100%**. We spent half of development on testing.
3. Thanks @maurelian for his contribution. We are happy to work with him!
4. We do not force developers to test our tools. We make tools that ready to use from scratch!

If you will have any other question about Solhint - I'll be glad to help!
\- Ilya

**Comment by maurelian** [comment]
Although my contribution was nothing but fixing a link in the Solhint docs, I am a fan of this linter. It just worked out of the box, and already had an integration with sublime.

**Comment by duaraghav8** [comment]
Thanks for the detailed comparison Ilya:)
A lot of what you pointed out has already been added in the latest version of Solium - `v1.0.8` or even earlier versions.

Since zeppelin uses 2 spaces for indentation, I believe its worth changing the configuration for both linters in your benchmarking.

As for speed, I really don't see any issue when I lint the contracts with solium.

```
time solium -d contracts/

contracts/Bounty.sol
  4:7     error      "./payment/PullPayment.sol": Import statements must use double quotes only.       quotes

...

  108:15    error      'now' is an alias for block.timestamp which can be influenced by miners to some extent. Avoid usage.    security/no-block-members
  111:30    error      'now' is an alias for block.timestamp which can be influenced by miners to some extent. Avoid usage.    security/no-block-members

✖ 67 errors, 52 warnings found.


real	0m1.534s
user	0m1.817s
sys	0m0.092s
```

Let me know what you think.

**Comment by melnikaite** [comment]
I think we must use Solhint at least while it has more rules than Solium, because security is extremely important for all Solidity community. @duaraghav8 just try to copy functionality and it will take some time, which we don't have, while @idrabenia made a great investigation job.

Moreover implementation of Solium is more elegant and easier to support, just look at implementation of the same `function ordering` rule at [Solium](https://github.com/duaraghav8/Solium/blob/master/lib/rules/function-order.js) and [Solhint](https://github.com/protofire/solhint/blob/master/lib/rules/order/function-order.js).

Also Solhint has better IDE support (support JetBrains IDEA). It's nice to have the same set of rules for IDE and in CI/CD system.

**Comment by duaraghav8** [comment]
Thanks @melnikaite. Since you & Ilya belong to the organisation that's sponsoring solhint, I believe its only fair that you support your linter:)

IMO we're all really just stretching this thread (apologies for the notifications, no more from me now).
Both have their pros & cons, I'll be here in case anyone has any questions about Solium.

**Comment by Shrugs** [comment]
We're currently using solium, but we can recreate this issue if moving to solhint is necessary in the future.
