### ISSUE TITLE
Crowdsale contracts use uint256 for timestamps, TokenTimelock uses uint64

### ISSUE THREAD

**Issue by Qqwy** [OpenZeppelin/zeppelin-solidity#517]
The Crowdsale contracts use uint256 for timestamps, but the TokenTimelock contract uses an uint64.

I expect using an uint64 consistently everywhere would be better, since the expected end of the universe would've passed 22 times the estimated current age of the universe before overflowing.

(An added advantage would of course be smaller contract size, i.e. lower gas costs).

**Comment by frangio** [comment]
Thanks fo reporting @Qqwy! The problem is actually in `TokenTimelock`. We should be using `uint256` everywhere.

`uint256` is the only integer size native to the EVM. For all other integer sizes, the Solidity compiler generates extra operations to e.g. truncate on overflow. Because of this, using uint64 doesn't really lead to smaller contracts or less gas costs.
