### ISSUE TITLE
Generate documentation site from NatSpec comments

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#594]
We should also delete the `docs` directory and make sure everything contained in it is present in the NatSpec comments.

**Comment by frangio** [comment]
@ajsantander if you won't be able to work on it let us know so someone else can pick it up. 🙂

**Comment by spalladino** [comment]
I've given a shot to [doxity](https://github.com/DigixGlobal/doxity/), and uploaded the output [here](https://openzeppelin.org/docs/) for review (source and ABI should be showing OK though, there was a problem with the directory structure when I rsync'ed). 

There is much room for improvement:

- Contracts are not listed in folders, which makes navigation difficult
- Every contract lists its functions and its ancestors', without distinction
- Several comments, such as devdoc annotations in the contract itself, are not shown (because they are not being picked up by natspec, it only picks devdoc from functions; see [this issue](https://github.com/ethereum/solidity/issues/1141) for more info)
- Multiline comments are not shown properly (see `MintableToken` functions), though this could be a problem on our comments, and not in the renderer
- Cosmetic details, such as OpenZeppelin branding, look and feel, etc

Also, I had to fork Doxity since it is using an out-of-date compiler, and remove `truffle.js` or the compilation via truffle failed. And, in order to compile all contracts in all nested folders, had to run:
```
doxity.js compile --src "$(find contracts -name *.sol | paste -sd ' ')"
```

I'm not sure how much this documentation provides in terms of help to a user. Perhaps with a bit more time, a better natspec parser (either patching solc's, or using a custom one), and a better template (I've been following [docusaurus](https://docusaurus.io/) closely) we can build something more interesting.

WDYT? Should I automate the process for building/deploying those docs, so we have something working _now_, or aim directly for a better option?

**Comment by frangio** [comment]
I agree with all your comments. Additionally, there are no docs for internal functions, which we need for stuff like `FinalizableCrowdsale#finalization`.

**Comment by spalladino** [comment]
Been playing a bit with @federicobond's antlr4 grammar and docusaurus [here](https://github.com/spalladino/solidity-docgen), and got to [this result](https://openzeppelin.org/test-docs/docs/api.html).

There is still a long way to go, but we have a full AST to work with here, and it's much easier to customise. The first step would be to actually _parse_ the natspec comments and use them in the markdown docs, as well as cleaning up the landing page and all the bells and whistles that docusaurus default template adds.

**Comment by federicobond** [comment]
Hey, glad you found my code helpful, and happy that this is finally coming together! Let me know if the license causes you any trouble so we can work it out.

**Comment by chuawengkwong** [comment]
Hi all : what is this all about
