### ISSUE TITLE
Rename Stoppable to Pausable 

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#6]
See Pause in http://vessenes.com/we-need-some-best-practices-for-smart-contracts/

**Comment by JGcarv** [comment]
Hi! I'm interested in tackling this issue, since I'm still scared of open source contributions, and this one seems pretty manageable. So, just to make sure, here's what I've done: I cloned the whole project and then replaced all instances of 'Stoppable' to 'Pausable'.

Now, How do I run tests for it?

Thanks in advance and sorry for the silly question!

**Comment by federicobond** [comment]
Hi @JGcarv, thanks for taking the time to contribute to OpenZeppelin.

You should be able to run the tests with `npm test` after installing all dependencies (`npm install`) and running an instance of `testrpc` in another console.

`testrpc` is installed with `npm install -g ethereumjs-testrpc`

**Comment by JGcarv** [comment]
Hey @federicobond , thanks for the reply!

So, I installed the dependencies and ran the tests(which were all passing) but when I tried to `git push origin myBranch` I got the following message:

`remote: Permission to OpenZeppelin/zeppelin-solidity.git denied to JGcarv.
fatal: unable to access 'https://github.com/OpenZeppelin/zeppelin-solidity.git/': The requested URL returned error: 403`

Do you have any idea what it might be? Thanks!

**Comment by federicobond** [comment]
Yes, you cannot push directly to the OpenZeppelin fork because you are not a collaborator. You should make your own fork on GitHub and configure your local clone to push there, like this:

```
git remote rename origin upstream
git remote add origin git@github.com:JGcarv/zeppelin-solidity.git
```

Once you do that, you will be able to push your branch:

```
git push -u origin myBranch
```

If you want to pull updates from the official fork later, you can then do so like this:
```
git pull upstream master
```

**Comment by JGcarv** [comment]
Yeah, that makes sense.

Anyway, I followed the steps and made a new pull request. Let me know if things do work out.

Also, thank you for your patience!

**Comment by maraoz** [comment]
Great work @JGcarv, closing this :)
