### ISSUE TITLE
Should we remove SafeMath#div?

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/zeppelin-solidity#655]
`SafeMath#div` doesn't perform any checks because division cannot overflow. It currently simply returns the result of the `/` operator. However, it may be considered "unsafe" the fact that integer division truncates the result, and this may be unexpected to users who think they are doing a safe operation, as implied by the name of the library.

I think we should address this, and consider either removing `div` from `SafeMath`, or adding checks to `SafeMath#div` ensure there was no truncation. The latter doesn't make much sense to me.

**Comment by spalladino** [comment]
> However, it may be considered "unsafe" the fact that integer division truncates the result, and this may be unexpected to users who think they are doing a safe operation, as implied by the name of the library.

This can be fixed with documentation, just adding a note that safemath only checks for overflows. Besides, Solidity has no float types, so it can be quite expected that a division will truncate.

>  ...adding checks to SafeMath#div ensure there was no truncation. The latter doesn't make much sense to me.

Same here.

> consider either removing div from SafeMath

I'd keep it for consistency. It's quite easy to scan a contract's code for arithmetic operators, to know where safemath can be potentially missing. If we remove it, we'd need to keep in mind that "some operators need safemath, others don't", which increases the risk of forgetting to switch to safemath.
