### ISSUE TITLE
can't catch the error "Error: VM Exception while processing transaction: revert"

### ISSUE THREAD

**Issue by leochan007** [OpenZeppelin/zeppelin-solidity#668]
## The Problem

this error can't be caught by expectThrow  if execute "web3.eth.sendTransaction" (not contract'call or transaction)

e.g.
expectThrow(web3.eth.sendTransaction({gas: gas_amt, from: accounts[1], to: AAA.address, 
      value: web3.toWei("1", "Ether")}, ""))

**Comment by Stradivario** [comment]
Having the same issue as you described....

![screenshot from 2018-01-14 16-09-33](https://user-images.githubusercontent.com/19847933/34917700-a0b02d88-f952-11e7-997a-fd48b620b4b9.png)

**Comment by leochan007** [comment]
@Stradivario yes. if the vm exception is from Contract's function call, it could be caught via expectThrow. and i don't know why.

**Comment by Stradivario** [comment]
Take a look here i create issue related with this bug https://github.com/trufflesuite/truffle/issues/748

**Comment by frangio** [comment]
Hello @Stradivario. The argument to [`expectThrow`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/v1.5.0/test/helpers/expectThrow.js) should be a `Promise` as returned by truffle-contract function calls. The reason `expectThrow` is not working here is that [`web3.eth.sendTransaction`](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction) returns a string containing the tx hash.

In order to use `expectThrow` here, you should probably do the following, as seen [in the Truffle documentation](http://truffleframework.com/docs/getting_started/contracts#sending-ether-to-a-contract).
```
expectThrow(AAA.send(web3.toWei(1, "ether"), { gas: gas_amt, from: accounts[1] }))
```
