### ISSUE TITLE
Use deed instead of token for ERC-721

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/zeppelin-solidity#709]
Regarding: https://github.com/OpenZeppelin/zeppelin-solidity/pull/627

Could this please be named a *deed* (in a deed/ folder) instead of a token?

---

https://github.com/ethereum/EIPs/pull/841

**Comment by fulldecent** [comment]
Also, you guys are pretty quick!

**Comment by buhrmi** [comment]
bro could you please stop your quest trying to rename everything "deed"? there are already lots of deployed contracts talking to each other using "token"

**Comment by fulldecent** [comment]
Okay.

We will have a vote/discussion something coming up to end this issue permanently.

https://github.com/ethereum/EIPs/pull/841#issuecomment-367723508

**Comment by carloschida** [comment]
@fulldecent I disagree with you here. If the final implementation of ERC721, say we decide to refer to it at the end as 'deed', is ERC20-compliant, then it is by all means an ERC20Token.

This is not contradictory. Consider the base tutorials of an OOL where a `Dog` is an `Animal` as much as a `Cat` is due to inheritance.

**Comment by fulldecent** [comment]
Closing this issue as a result of 

https://github.com/ethereum/EIPs/pull/841/commits/1eeddf7a575d5f9bfee55cce4f0b7088cb0719ad

https://github.com/ethereum/EIPs/pull/841#issuecomment-368729414
