### ISSUE TITLE
An improvement in pausable.sol

### ISSUE THREAD

**Issue by AyushyaChitransh** [OpenZeppelin/zeppelin-solidity#723]
### Togglable

As of its current implementation, `pausable.sol` works as a toggle switch to `turn_on` and `turn_off` certain functionalities. If we just want to have a toggle functionality, then we can inherit a different contract with name like `togglable`. The name `pausable` leads to notions of time.

### Pausable

If we are to have a `pausable` contract, it should have variables like `startTime` and `endTime` defined in itself. Then pausable would be able to track duration of how long it was paused and update the `endTime` when it is resumed.

**Comment by federicobond** [comment]
Hi @AyushyaChitransh! Thanks for your suggestion. Do you have a use case in mind that benefits from this sort of time-tracking being performed on-chain?

**Comment by AyushyaChitransh** [comment]
@federicobond Pausable instinctively refers to something which has been continuing in time, hence time-tracking. Anything that requires to be paused, will pause something which has a duration. And the integrity of that duration is retained by resume function 

Use cases:
 - ICOs generally have a starting time and an ending time, so they would benefit if `pause` worked as `pause` and on `resume` it updated end time to adjust the original duration.

I cannot think of any other popular use case as of now.

**Comment by federicobond** [comment]
Thank you for your answer @AyushyaChitransh. I think we are best keeping the current Pausable behaviour minimal for now, since it's not a requirement that we have seen coming up for most use cases, and it would be easy to add if required.

At OpenZeppelin, we aim to cover the most general use cases with well audited contracts. This requires us to be very careful with any extra assumptions that we make about how they will be used, especially considering that each extra storage slot used costs quite a bit of gas.
