### ISSUE TITLE
How does the versioning work?

### ISSUE THREAD

**Issue by marti-1** [OpenZeppelin/zeppelin-solidity#764]
Do you follow the MAJOR.MINOR.PATCH semantic? Because if yes, then 1.7.0 breaks backwards compatibility.

**Comment by vidorge** [comment]
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/README.md#getting-started

> **Note that OpenZeppelin does not currently follow semantic versioning**. You may encounter breaking changes upon a minor version bump.

**Comment by Qqwy** [comment]
What is the reason for _not_ following Semver?

**Comment by Qqwy** [comment]
Can someone please expand on this issue?

**Comment by Qqwy** [comment]
Dear maintainers of OpenZeppelin; we are still waiting for an answer. Please respond at your earliest convenience.

**Comment by Shrugs** [comment]
the reasoning is basically: we want to feel free to make breaking changes often. We should be in 0.x.y but it's too late for that.

we updated the installation instructions to save the exact version instead of the semver expression, so it shouldn't cause unintended upgrades

moving to semver is planned in the future, but I'm not sure what that timeline is
