### ISSUE TITLE
📈 Make BurnableToken consistent w/ MintableToken (i.e. onlyOwner and burnFrom configurable)

### ISSUE THREAD

**Issue by mjdietzx** [OpenZeppelin/zeppelin-solidity#785]
## 🎉 Description

`MintableToken` has been improved such that only the original 'owner' of the contract can [mint tokens](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/ERC20/MintableToken.sol#L31), and the `address` that receives the minted tokens can be chosen.

I think it would be more standard/useful and improve consistency if `BurnableToken` had these features added as well (currently any address can burn a token, and it defaults to burning tokens from `msg.sender`.

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using? `master branch`
- What network are you deploying to? testrpc? **Ganache**? Ropsten?
- How are you deploying your OpenZeppelin-backed contracts? **truffle**? Remix? Let us know!

## 🔢 Code To Reproduce Issue [ Good To Have ]

This is what a PR adding these features could look like (I will make this PR w/ associated unit-tests).

```solidity
/**
 * @title Burnable Token
 * @dev Token that can be irreversibly burned (destroyed).
 */
contract BurnableToken is BasicToken, Ownable {

  event Burn(address indexed burner, uint256 value);

  /**
   * @dev Burns a specific amount of tokens.
   * @param _from The address whose tokens will be burned.
   * @param _value The amount of token to be burned.
   */
  function burn(address _from, uint256 _value) onlyOwner public {
    require(_value <= balances[_from]);
    // no need to require value <= totalSupply, since that would imply the
    // sender's balance is greater than the totalSupply, which *should* be an assertion failure

    balances[_from] = balances[_from].sub(_value);
    totalSupply_ = totalSupply_.sub(_value);
    Burn(_from, _value);
    Transfer(_from, address(0), _value);
  }
}
```

**Comment by Shrugs** [comment]
I'm not sure a publicly callable burn function to allow the owner of the token to burn anyone's tokens is a good idea. The mintable implementation makes sense because you can call `stopMinting` and remove the ability for anyone to mint more tokens. But that's not possible with burning because you want to be able to burn your own tokens at any time. I can't think of any case where I'd want the owner of a token contract to be able to burn my tokens at any time. Perhaps a better idea is to allow a burnable token to use the `approve()` feature for delegating the burning of one's tokens (but at the same time, it might be much more popular/necessary for contracts to enforce that potentially-burnable tokens must be escrowed to avoid people sending them away before they're burned).

I'm not sure this is a feature, and if it is something that people want, it'd definitely need to be another inheritable version of `Token`. Regardless, I'm not sure if this is something that should be in OZ at all, since it's such a specific feature. Let me know if you think otherwise.

**Comment by Shrugs** [comment]
Ah, I see how this would be used in a situation where only another contract can be the owner of a token. This could be useful, but is almost definitely not something that should be on `BurnableToken` and should instead be in a token derivative called `ControlledToken` or something, where a contract can mint and burn at-will, constrained by its own programming.

**Comment by mjdietzx** [comment]
Ah, I see. Yeah I agree, this definitely doesn't belong in BurnableToken. Thanks, will close this issue and corresponding PR!

**Comment by liwei00wade** [comment]
I don't know how to implemented this feature,
Could you please give me an example.

**Comment by liwei00wade** [comment]
this definitely doesn't belong in BurnableToken

Why ??

how to  write a ControlledToken ?

**Comment by shrugs** [comment]
@liwei00wade simply extend `StandardToken` and add a method that allows the owner of a contract to burn tokens from anyone

```
function burnFrom(address _from, uint256 _amount) onlyOwner public {
  _burn(_from, _amount);
}
```

that's it
