### ISSUE TITLE
Make the crowdsale Destructible by default

### ISSUE THREAD

**Issue by subramanianv** [OpenZeppelin/zeppelin-solidity#852]
## 🎉 Description

Often, mistakes are made in the parameters to the crowdsale. To prevent further damage,  we should make the crowdsale example or the base crowdsale destructible or token destructible by default.
- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

**Comment by PhABC** [comment]
Could you provide more rationale as to why they should be made destructible? 

Unless you share the address and publish the code, it's unlikely people will send funds anyway. In addition, people can still send funds even once a contract is destructed, which would make things worst in this scenario considering the funds would be lost forever.

**Comment by jacktang** [comment]
I agreed with @PhABC. Destructible op is very risky and I think it should be removed

**Comment by jacktang** [comment]
BTW, does anyone explain why `Destructible` constructor is `payable`?
```
contract Destructible is Ownable {

  function Destructible() public payable { }
```

**Comment by Shrugs** [comment]
A more appropriate change would be to add a `DestructibleCrowdsale` that, perhaps, inherits from `FinalizableCrowdsale` in order to destroy itself after it's been completed.

Making a crowdsale destructible by default isn't a reasonable decision, but I've created a separate issue to track the `DestructibleCrowdsale` addition: https://github.com/OpenZeppelin/zeppelin-solidity/issues/862

@jacktang  In general, all constructors are `public payable` to allow someone to send ether to the contract (and anything that inherits it) at deploy-time. Probably a combination of convention and simplicity, but I'd be interested in knowing for sure.
