### ISSUE TITLE
Crowdsale.sol contract has a bug in setting rate

### ISSUE THREAD

**Issue by sheraz104** [OpenZeppelin/zeppelin-solidity#857]
The **Wei** received in transaction to fallback function are **multiplied** to rate and there is a check for rate in constructor  (see second screenshot) for it to be **greater than 0**. Currently, if we want to set rate for a single token to 10000 **Wei**, we would have to pass rate's value in the format of 0.000000000000001 and the transaction will **fail** and will only pass if we set the rate such that
we can set rate of **2 token for 1** **Wei**, but not **1 token for 2** **Wei**.

![image](https://user-images.githubusercontent.com/37038761/38159676-41410382-34b6-11e8-92bf-e27d1d37855e.png)

![image](https://user-images.githubusercontent.com/37038761/38159682-5127aad0-34b6-11e8-8831-771fd727ad52.png)

I made the code work by using division instead of multiply and providing the rate's value in the format of 1000000000000..

**Comment by jacktang** [comment]
@sheraz104 check the `rate` comment in `Crowdsale.sol`, it said `How many token units a buyer gets per wei`. `1 token for 2 Wei` means the `price`.

**Comment by Hashedhash** [comment]
@jacktang If token supply is more or equal 1e18 the current implementation works. What if there are only 100 tokens in the contract?

**Comment by sheraz104** [comment]
@jacktang exactly. Even when the tokens are 1e18, which is a huge amount, if I'm not wrong the crowdsale can be bought for 1 ether.

**Comment by shyheim103** [comment]
@sheraz104 agreed. I've been trying to figure out why it was written this way for the past week. Glad someone else has noticed this.

**Comment by Shrugs** [comment]
note that there's a difference between `1 TKN` and `1 TKNbit` where what people usually call "one token" is actually `1 * 1e18 TKNbits`. This is the same relationship that ether and wei have. And what you're always doing calculations in is `TKNbits`.

So if you want to issue someone "one token for every 2 wei" and your decimals are `18`, your rate is actually something like `0.5e17`. Then, when I send you 2 wei, you issue me `2 * 0.5e17 TKNbits`, which is exactly equal to `1 TKN`.

And, to show the answer to the first question, "one token for 10000 Wei", your rate should be `1e14`. Then, for each wei that is sent, I'm issued `1e14 TKNbits`, which, once You send 10000 wei will be `10000 * 1e14 === 1e18`. And then because your decimals are `18`, that's displayed as `1 TKN`.

---

Issuing less than 1 TKNbit/wei isn't really useful in practice, but there are a few ways to do it:

You're correct that because of the multiplication, you can't issue less TKNbits than the wei that was provided, but you _can_ issue less TKN, total, by changing your decimals. If you change your decimals to `10`, for example, you can now use a rate of `1` to say that "one TKNbit for one wei", meaning that it costs `10 Gwei` to own `1 TKN`. 

If you don't want to change your decimals, you can also just inherit from crowdsale and (i) change the rate to a divisor and then (ii) change `_getTokenAmount ` to use div and (iii) tell your users to just ignore the rounding errors

**Comment by linkdesu** [comment]
Finally found the truth after hours of debug , THX ! 😂

But why not write things so important in document ?!?!

**Comment by shrugs** [comment]
@linkdesu You should always, always operate in the smallest number of a currency when doing automatic operations on it. This is generally-well-known in programming and mentioned a variety of times in the ethereum docs.

We will add a specific note to this contract, thank you for your report
